### ISSUE TITLE
Rapp의 public parameter parsing 시 key value 가 2-depth 이상인 경우 에러 발생

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_protocols_web#32]
Rapp 의 public parameter 는 yaml 형식으로 작성됩니다. 

대표적인 예로 [talker](https://github.com/robotics-in-concert/rocon_app_platform/blob/indigo/rocon_apps/apps/talker/talker.parameters
) 의 경우  
```
message: hello world
frequency: 10
```
처러 단순한 key value를 같습니다. 
하지만, [room_checker](https://github.com/robotics-in-concert/rocon_demos/blob/concert_common_rapps/concert_demo_rapps/rapps/room_checker/room_checker.parameters)
```
time_interval: 1
rooms:
    - meeting_room: "motion_detector_2"
    - conf_room: "motion_detector_1"
    - small_conf_room: "motion_detector_3"
```
과 같이 2depth 의 파라미터 구조를 같는 경우, 이를 fetch 하다가 에러가 발생합니다. 

[파마미터를 key value로 parsing 하는 부분](https://github.com/robotics-in-concert/rocon_protocols_web/blob/master/rocon_protocols_web_fetch/lib/utils.js#L23-L30)을 살펴 보면, 
1depth 에 대해서만 지원합니다. 

만약 이 부분이 업데이트가 된다면 , rocon composer의 blockly workflow 저작 ui도 개선되어야 합니다.
